# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6d3a7f00beb201bbbd99b964fc7712738909e3c0b634a2261b09c3664d0ece16846b2ca5f9dac8ef1ac3a2e193163cbf1b1d73e97996b27751bf2f0d118d300

test:
  secret_key_base: 877fa36e72ac3f2e78505e35717e867560e57c44645f0644a1305a1f9b2ecadfe0aad826e9c9abaa1e290c082f89f2dc75b5abf24c6203b9baa51db05c7f729e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
